name: smartclassmate
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_heatmap_calendar: ^1.0.5
  another_stepper: ^1.2.2
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  theme_provider: ^0.6.0
  file_picker: ^6.1.1
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
